Repository betagouv/mon-entreprise, pull requests merged in 2021-01, with the labels that each got.

#1330 Supprime Ramda du moteur
  modele-social/règles/salarié.yaml
  publicodes/core/package.json
  publicodes/core/source/AST/graph.ts
  publicodes/core/source/AST/index.ts
  publicodes/core/source/evaluation.ts
  publicodes/core/source/format.ts
  publicodes/core/source/index.ts
  publicodes/core/source/mecanisms/condition-allof.ts
  publicodes/core/source/mecanisms/condition-oneof.ts
  publicodes/core/source/mecanisms/min.ts
  publicodes/core/source/mecanisms/operation.ts
  publicodes/core/source/mecanisms/reduction.ts
  publicodes/core/source/mecanisms/situation.ts
  publicodes/core/source/mecanisms/synchronisation.ts
  publicodes/core/source/mecanisms/trancheUtils.ts
  publicodes/core/source/mecanisms/variations.ts
  publicodes/core/source/parse.ts
  publicodes/core/source/parsePublicodes.ts
  publicodes/core/source/replacement.tsx
  publicodes/core/source/rule.ts
  publicodes/core/source/ruleUtils.ts
  publicodes/core/source/units.ts
Labels: 🐎 performances

#1359 Fix modale qui s'affiche tout en haut
  mon-entreprise/source/site/entry.en.tsx
  mon-entreprise/source/site/entry.fr.tsx
  mon-entreprise/webpack.prod.js
Labels: 🐛 bug

#1377 Désactive la taxe sur les salaire pour le cas standard
  modele-social/règles/entreprise-établissement.yaml
  mon-entreprise/source/locales/rules-en.yaml
  mon-entreprise/source/locales/ui-en.yaml
  mon-entreprise/source/pages/Simulateurs/SalariéSimulation.tsx
  mon-entreprise/test/regressions/__snapshots__/simulations.jest.js.snap
Labels: 🐛 bug, 📕 législation

#1385 :bug: :hammer: Désactive la retraite complémentaire pour les médecins (<2 ans)
  modele-social/règles/profession-libérale.yaml
  mon-entreprise/test/regressions/__snapshots__/simulations.jest.js.snap
  mon-entreprise/test/regressions/simulations-professions-libérales.yaml
Labels: 🏓 retour utilisateur, 📕 législation

#1387 Répare un bug dans l'affichage des variations
  publicodes/core/source/mecanisms/variations.ts
Labels: ⚙️ publicodes, 🐛 bug
