Repository betagouv/mon-entreprise, pull requests merged in 2024-07, with the labels that each got.

#2984 Supprime l'intégration Zammad
  .github/workflows/deploy.yaml
  .github/workflows/pr-cleanup.yaml
  .github/workflows/test.yaml
  .github/workflows/update-stats.yaml
  .github/workflows/zammad-bot.yaml
  site/.env.template
  site/netlify.base.toml
  site/scripts/stats/fetch-stats.js
Labels: 💻 technique

#2985 Met à jour les liens morts
  modele-social/règles/entreprise/établissement.publicodes
  site/source/locales/ui-en.yaml
  site/source/locales/ui-fr.yaml
  site/source/pages/assistants/declaration-charges-sociales-independant/components/RésultatSimple.tsx
  site/source/pages/integration/components/CasParticuliers.tsx
Labels: 🖊 contenu

#2966 Update custom-tags.ts
  site/scripts/NAFAndGuichetData/NAF-search/custom-tags.ts
Labels: 📕 législation, S

#3029 ajoute la précision (droit commun) pour autre convention collective
  modele-social/règles/salarié/conventions-collectives/droit-commun.publicodes
Labels: 🤩 ux

#3030 feat(artistes-auteurs): met à jour le lien vers le guide IRCEC 2024
  modele-social/règles/artiste-auteur.publicodes
Labels: 🐛 bug, 🖊 contenu
